// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory.sql

package database

import (
	"context"
	"time"
)

const adjustInventoryStock = `-- name: AdjustInventoryStock :one
UPDATE inventory
SET
  stock_qty = stock_qty + ?,
  updated_at = CURRENT_TIMESTAMP
WHERE product_id = ?
RETURNING product_id, stock_qty, reorder_level, unit, track_stock, updated_at
`

type AdjustInventoryStockParams struct {
	StockQty  float64 `json:"stock_qty"`
	ProductID int64   `json:"product_id"`
}

func (q *Queries) AdjustInventoryStock(ctx context.Context, arg AdjustInventoryStockParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, adjustInventoryStock, arg.StockQty, arg.ProductID)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StockQty,
		&i.ReorderLevel,
		&i.Unit,
		&i.TrackStock,
		&i.UpdatedAt,
	)
	return i, err
}

const createInventoryMovement = `-- name: CreateInventoryMovement :one
INSERT INTO inventory_movements (product_id, change_qty, reason, reference)
VALUES (?, ?, ?, ?)
RETURNING id, product_id, change_qty, reason, reference, created_at
`

type CreateInventoryMovementParams struct {
	ProductID int64   `json:"product_id"`
	ChangeQty float64 `json:"change_qty"`
	Reason    string  `json:"reason"`
	Reference string  `json:"reference"`
}

func (q *Queries) CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error) {
	row := q.db.QueryRowContext(ctx, createInventoryMovement,
		arg.ProductID,
		arg.ChangeQty,
		arg.Reason,
		arg.Reference,
	)
	var i InventoryMovement
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.ChangeQty,
		&i.Reason,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const getProduct = `-- name: GetProduct :one
SELECT
  mi.id,
  mi.category_id,
  COALESCE(mc.name, '') AS category_name,
  mi.name,
  mi.description,
  mi.price_cents,
  mi.cost_cents,
  mi.image_url,
  mi.sku,
  mi.item_type,
  mi.sort_order,
  mi.active,
  COALESCE(inv.stock_qty, 0) AS stock_qty,
  COALESCE(inv.reorder_level, 0) AS reorder_level,
  COALESCE(inv.unit, 'pcs') AS unit,
  COALESCE(inv.track_stock, 1) AS track_stock,
  CASE
    WHEN COALESCE(inv.track_stock, 1) = 1 AND COALESCE(inv.stock_qty, 0) <= 0 THEN 1
    ELSE 0
  END AS out_of_stock,
  mi.created_at
FROM menu_items mi
LEFT JOIN menu_categories mc ON mc.id = mi.category_id
LEFT JOIN inventory inv ON inv.product_id = mi.id
WHERE mi.id = ?
LIMIT 1
`

type GetProductRow struct {
	ID           int64     `json:"id"`
	CategoryID   int64     `json:"category_id"`
	CategoryName string    `json:"category_name"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	PriceCents   int64     `json:"price_cents"`
	CostCents    int64     `json:"cost_cents"`
	ImageUrl     string    `json:"image_url"`
	Sku          string    `json:"sku"`
	ItemType     string    `json:"item_type"`
	SortOrder    int64     `json:"sort_order"`
	Active       int64     `json:"active"`
	StockQty     float64   `json:"stock_qty"`
	ReorderLevel float64   `json:"reorder_level"`
	Unit         string    `json:"unit"`
	TrackStock   int64     `json:"track_stock"`
	OutOfStock   int64     `json:"out_of_stock"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) GetProduct(ctx context.Context, id int64) (GetProductRow, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i GetProductRow
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.CategoryName,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.CostCents,
		&i.ImageUrl,
		&i.Sku,
		&i.ItemType,
		&i.SortOrder,
		&i.Active,
		&i.StockQty,
		&i.ReorderLevel,
		&i.Unit,
		&i.TrackStock,
		&i.OutOfStock,
		&i.CreatedAt,
	)
	return i, err
}

const listInventoryMovements = `-- name: ListInventoryMovements :many
SELECT
  im.id,
  im.product_id,
  COALESCE(mi.name, '') AS product_name,
  im.change_qty,
  im.reason,
  im.reference,
  im.created_at
FROM inventory_movements im
JOIN menu_items mi ON mi.id = im.product_id
ORDER BY im.created_at DESC
LIMIT ?
`

type ListInventoryMovementsRow struct {
	ID          int64     `json:"id"`
	ProductID   int64     `json:"product_id"`
	ProductName string    `json:"product_name"`
	ChangeQty   float64   `json:"change_qty"`
	Reason      string    `json:"reason"`
	Reference   string    `json:"reference"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) ListInventoryMovements(ctx context.Context, limit int64) ([]ListInventoryMovementsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryMovements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryMovementsRow
	for rows.Next() {
		var i ListInventoryMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.ChangeQty,
			&i.Reason,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT
  mi.id,
  mi.category_id,
  COALESCE(mc.name, '') AS category_name,
  mi.name,
  mi.description,
  mi.price_cents,
  mi.cost_cents,
  mi.image_url,
  mi.sku,
  mi.item_type,
  mi.sort_order,
  mi.active,
  COALESCE(inv.stock_qty, 0) AS stock_qty,
  COALESCE(inv.reorder_level, 0) AS reorder_level,
  COALESCE(inv.unit, 'pcs') AS unit,
  COALESCE(inv.track_stock, 1) AS track_stock,
  CASE
    WHEN COALESCE(inv.track_stock, 1) = 1 AND COALESCE(inv.stock_qty, 0) <= 0 THEN 1
    ELSE 0
  END AS out_of_stock,
  mi.created_at
FROM menu_items mi
LEFT JOIN menu_categories mc ON mc.id = mi.category_id
LEFT JOIN inventory inv ON inv.product_id = mi.id
ORDER BY mi.active DESC, mi.sort_order, mi.name
`

type ListProductsRow struct {
	ID           int64     `json:"id"`
	CategoryID   int64     `json:"category_id"`
	CategoryName string    `json:"category_name"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	PriceCents   int64     `json:"price_cents"`
	CostCents    int64     `json:"cost_cents"`
	ImageUrl     string    `json:"image_url"`
	Sku          string    `json:"sku"`
	ItemType     string    `json:"item_type"`
	SortOrder    int64     `json:"sort_order"`
	Active       int64     `json:"active"`
	StockQty     float64   `json:"stock_qty"`
	ReorderLevel float64   `json:"reorder_level"`
	Unit         string    `json:"unit"`
	TrackStock   int64     `json:"track_stock"`
	OutOfStock   int64     `json:"out_of_stock"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) ListProducts(ctx context.Context) ([]ListProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.CostCents,
			&i.ImageUrl,
			&i.Sku,
			&i.ItemType,
			&i.SortOrder,
			&i.Active,
			&i.StockQty,
			&i.ReorderLevel,
			&i.Unit,
			&i.TrackStock,
			&i.OutOfStock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertInventory = `-- name: UpsertInventory :one
INSERT INTO inventory (product_id, stock_qty, reorder_level, unit, track_stock, updated_at)
VALUES (?, ?, ?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT(product_id) DO UPDATE SET
  stock_qty = excluded.stock_qty,
  reorder_level = excluded.reorder_level,
  unit = excluded.unit,
  track_stock = excluded.track_stock,
  updated_at = CURRENT_TIMESTAMP
RETURNING product_id, stock_qty, reorder_level, unit, track_stock, updated_at
`

type UpsertInventoryParams struct {
	ProductID    int64   `json:"product_id"`
	StockQty     float64 `json:"stock_qty"`
	ReorderLevel float64 `json:"reorder_level"`
	Unit         string  `json:"unit"`
	TrackStock   int64   `json:"track_stock"`
}

func (q *Queries) UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, upsertInventory,
		arg.ProductID,
		arg.StockQty,
		arg.ReorderLevel,
		arg.Unit,
		arg.TrackStock,
	)
	var i Inventory
	err := row.Scan(
		&i.ProductID,
		&i.StockQty,
		&i.ReorderLevel,
		&i.Unit,
		&i.TrackStock,
		&i.UpdatedAt,
	)
	return i, err
}
