// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package database

import (
	"context"
)

const listCategories = `-- name: ListCategories :many
SELECT id, name, sort_order, active FROM menu_categories WHERE active = 1 ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]MenuCategory, error) {
	rows, err := q.db.QueryContext(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuCategory
	for rows.Next() {
		var i MenuCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.SortOrder,
			&i.Active,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItems = `-- name: ListMenuItems :many
SELECT id, category_id, name, description, price_cents, image_url, active, created_at
FROM menu_items
WHERE active = 1
ORDER BY category_id, name
`

func (q *Queries) ListMenuItems(ctx context.Context) ([]MenuItem, error) {
	rows, err := q.db.QueryContext(ctx, listMenuItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.ImageUrl,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMenuItem = `-- name: UpsertMenuItem :one
INSERT INTO menu_items (category_id, name, description, price_cents, image_url, active)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
  category_id = excluded.category_id,
  name = excluded.name,
  description = excluded.description,
  price_cents = excluded.price_cents,
  image_url = excluded.image_url,
  active = excluded.active
RETURNING id, category_id, name, description, price_cents, image_url, active, created_at
`

type UpsertMenuItemParams struct {
	CategoryID  int64  `json:"category_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	PriceCents  int64  `json:"price_cents"`
	ImageUrl    string `json:"image_url"`
	Active      int64  `json:"active"`
}

func (q *Queries) UpsertMenuItem(ctx context.Context, arg UpsertMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, upsertMenuItem,
		arg.CategoryID,
		arg.Name,
		arg.Description,
		arg.PriceCents,
		arg.ImageUrl,
		arg.Active,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.ImageUrl,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}
