// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
	"time"
)

type Ingredient struct {
	ID          int64   `json:"id"`
	Name        string  `json:"name"`
	Unit        string  `json:"unit"`
	StockQty    float64 `json:"stock_qty"`
	LowStockQty float64 `json:"low_stock_qty"`
}

type MenuCategory struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	SortOrder int64  `json:"sort_order"`
	Active    int64  `json:"active"`
}

type MenuItem struct {
	ID          int64     `json:"id"`
	CategoryID  int64     `json:"category_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	PriceCents  int64     `json:"price_cents"`
	ImageUrl    string    `json:"image_url"`
	Active      int64     `json:"active"`
	CreatedAt   time.Time `json:"created_at"`
}

type MenuItemIngredient struct {
	MenuItemID   int64   `json:"menu_item_id"`
	IngredientID int64   `json:"ingredient_id"`
	Qty          float64 `json:"qty"`
}

type Order struct {
	ID            int64         `json:"id"`
	TableID       sql.NullInt64 `json:"table_id"`
	CustomerName  string        `json:"customer_name"`
	Status        string        `json:"status"`
	SubtotalCents int64         `json:"subtotal_cents"`
	VatCents      int64         `json:"vat_cents"`
	TotalCents    int64         `json:"total_cents"`
	Source        string        `json:"source"`
	CreatedAt     time.Time     `json:"created_at"`
	UpdatedAt     time.Time     `json:"updated_at"`
}

type OrderItem struct {
	ID             int64  `json:"id"`
	OrderID        int64  `json:"order_id"`
	MenuItemID     int64  `json:"menu_item_id"`
	Quantity       int64  `json:"quantity"`
	UnitPriceCents int64  `json:"unit_price_cents"`
	Notes          string `json:"notes"`
	Status         string `json:"status"`
}

type Payment struct {
	ID          int64     `json:"id"`
	OrderID     int64     `json:"order_id"`
	Method      string    `json:"method"`
	AmountCents int64     `json:"amount_cents"`
	Status      string    `json:"status"`
	Reference   string    `json:"reference"`
	CreatedAt   time.Time `json:"created_at"`
}

type RestaurantTable struct {
	ID        int64     `json:"id"`
	Number    string    `json:"number"`
	Seats     int64     `json:"seats"`
	Status    string    `json:"status"`
	QrToken   string    `json:"qr_token"`
	CreatedAt time.Time `json:"created_at"`
}

type User struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	Role         string    `json:"role"`
	Active       int64     `json:"active"`
	CreatedAt    time.Time `json:"created_at"`
}
