// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package database

import (
	"context"
	"database/sql"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (table_id, customer_name, source, subtotal_cents, vat_cents, total_cents)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, table_id, customer_name, status, subtotal_cents, vat_cents, total_cents, source, created_at, updated_at
`

type CreateOrderParams struct {
	TableID       sql.NullInt64 `json:"table_id"`
	CustomerName  string        `json:"customer_name"`
	Source        string        `json:"source"`
	SubtotalCents int64         `json:"subtotal_cents"`
	VatCents      int64         `json:"vat_cents"`
	TotalCents    int64         `json:"total_cents"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder,
		arg.TableID,
		arg.CustomerName,
		arg.Source,
		arg.SubtotalCents,
		arg.VatCents,
		arg.TotalCents,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.CustomerName,
		&i.Status,
		&i.SubtotalCents,
		&i.VatCents,
		&i.TotalCents,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, menu_item_id, quantity, unit_price_cents, notes)
VALUES (?, ?, ?, ?, ?)
RETURNING id, order_id, menu_item_id, quantity, unit_price_cents, notes, status
`

type CreateOrderItemParams struct {
	OrderID        int64  `json:"order_id"`
	MenuItemID     int64  `json:"menu_item_id"`
	Quantity       int64  `json:"quantity"`
	UnitPriceCents int64  `json:"unit_price_cents"`
	Notes          string `json:"notes"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRowContext(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Quantity,
		arg.UnitPriceCents,
		arg.Notes,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Quantity,
		&i.UnitPriceCents,
		&i.Notes,
		&i.Status,
	)
	return i, err
}

const deductIngredientStock = `-- name: DeductIngredientStock :exec
UPDATE ingredients
SET stock_qty = stock_qty - (
  SELECT mii.qty * ? FROM menu_item_ingredients AS mii WHERE mii.menu_item_id = ? AND mii.ingredient_id = ingredients.id
)
WHERE ingredients.id IN (SELECT mii.ingredient_id FROM menu_item_ingredients AS mii WHERE mii.menu_item_id = ?)
`

type DeductIngredientStockParams struct {
	Qty          float64 `json:"qty"`
	MenuItemID   int64   `json:"menu_item_id"`
	MenuItemID_2 int64   `json:"menu_item_id_2"`
}

func (q *Queries) DeductIngredientStock(ctx context.Context, arg DeductIngredientStockParams) error {
	_, err := q.db.ExecContext(ctx, deductIngredientStock, arg.Qty, arg.MenuItemID, arg.MenuItemID_2)
	return err
}

const getMenuItem = `-- name: GetMenuItem :one
SELECT id, category_id, name, description, price_cents, image_url, active, created_at FROM menu_items WHERE id = ?
`

func (q *Queries) GetMenuItem(ctx context.Context, id int64) (MenuItem, error) {
	row := q.db.QueryRowContext(ctx, getMenuItem, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Name,
		&i.Description,
		&i.PriceCents,
		&i.ImageUrl,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const listOrderItems = `-- name: ListOrderItems :many
SELECT id, order_id, menu_item_id, quantity, unit_price_cents, notes, status FROM order_items WHERE order_id = ?
`

func (q *Queries) ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error) {
	rows, err := q.db.QueryContext(ctx, listOrderItems, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Quantity,
			&i.UnitPriceCents,
			&i.Notes,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrders = `-- name: ListOrders :many
SELECT id, table_id, customer_name, status, subtotal_cents, vat_cents, total_cents, source, created_at, updated_at
FROM orders
ORDER BY created_at DESC
LIMIT ?
`

func (q *Queries) ListOrders(ctx context.Context, limit int64) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TableID,
			&i.CustomerName,
			&i.Status,
			&i.SubtotalCents,
			&i.VatCents,
			&i.TotalCents,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders SET status = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
RETURNING id, table_id, customer_name, status, subtotal_cents, vat_cents, total_cents, source, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, updateOrderStatus, arg.Status, arg.ID)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.CustomerName,
		&i.Status,
		&i.SubtotalCents,
		&i.VatCents,
		&i.TotalCents,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
