// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package database

import (
	"context"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id, method, amount_cents, status, reference)
VALUES (?, ?, ?, ?, ?)
RETURNING id, order_id, method, amount_cents, status, reference, created_at
`

type CreatePaymentParams struct {
	OrderID     int64  `json:"order_id"`
	Method      string `json:"method"`
	AmountCents int64  `json:"amount_cents"`
	Status      string `json:"status"`
	Reference   string `json:"reference"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRowContext(ctx, createPayment,
		arg.OrderID,
		arg.Method,
		arg.AmountCents,
		arg.Status,
		arg.Reference,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Method,
		&i.AmountCents,
		&i.Status,
		&i.Reference,
		&i.CreatedAt,
	)
	return i, err
}

const listPayments = `-- name: ListPayments :many
SELECT id, order_id, method, amount_cents, status, reference, created_at FROM payments ORDER BY created_at DESC LIMIT ?
`

func (q *Queries) ListPayments(ctx context.Context, limit int64) ([]Payment, error) {
	rows, err := q.db.QueryContext(ctx, listPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Payment
	for rows.Next() {
		var i Payment
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Method,
			&i.AmountCents,
			&i.Status,
			&i.Reference,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
