// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
	"database/sql"
)

type Querier interface {
	ActiveSessionCount(ctx context.Context) (int64, error)
	AdjustInventoryStock(ctx context.Context, arg AdjustInventoryStockParams) (Inventory, error)
	ArchiveMenuItem(ctx context.Context, id int64) error
	BestSellingItems(ctx context.Context, limit int64) ([]BestSellingItemsRow, error)
	CloseSession(ctx context.Context, id int64) error
	ConfirmPayment(ctx context.Context, arg ConfirmPaymentParams) (ConfirmPaymentRow, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (MenuCategory, error)
	CreateInventoryMovement(ctx context.Context, arg CreateInventoryMovementParams) (InventoryMovement, error)
	CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (CreateMenuItemRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (CreateOrderRow, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (CreatePaymentRow, error)
	CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (CreateTableRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DailySales(ctx context.Context, limit int64) ([]DailySalesRow, error)
	GetLatestOrderForSession(ctx context.Context, sessionID sql.NullInt64) (GetLatestOrderForSessionRow, error)
	GetMenuItem(ctx context.Context, id int64) (GetMenuItemRow, error)
	GetOrder(ctx context.Context, id int64) (GetOrderRow, error)
	GetPaymentsForOrder(ctx context.Context, orderID int64) ([]GetPaymentsForOrderRow, error)
	GetProduct(ctx context.Context, id int64) (GetProductRow, error)
	GetReceiptByOrderID(ctx context.Context, orderID int64) (Receipt, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSettings(ctx context.Context) (Setting, error)
	GetTableByID(ctx context.Context, id int64) (GetTableByIDRow, error)
	GetTableByIdentifier(ctx context.Context, arg GetTableByIdentifierParams) (GetTableByIdentifierRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListAdminCategories(ctx context.Context) ([]MenuCategory, error)
	ListAdminMenuItems(ctx context.Context) ([]ListAdminMenuItemsRow, error)
	ListCategories(ctx context.Context) ([]MenuCategory, error)
	ListInventoryMovements(ctx context.Context, limit int64) ([]ListInventoryMovementsRow, error)
	ListMenuItems(ctx context.Context) ([]ListMenuItemsRow, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]ListOrderItemsRow, error)
	ListOrders(ctx context.Context, limit int64) ([]ListOrdersRow, error)
	ListPayments(ctx context.Context, limit int64) ([]ListPaymentsRow, error)
	ListProducts(ctx context.Context) ([]ListProductsRow, error)
	ListTables(ctx context.Context) ([]ListTablesRow, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	LowStockProducts(ctx context.Context) ([]LowStockProductsRow, error)
	OpenOrderCount(ctx context.Context) (int64, error)
	PaymentMethodStats(ctx context.Context) ([]PaymentMethodStatsRow, error)
	RevenueSnapshot(ctx context.Context) (RevenueSnapshotRow, error)
	SaveSettings(ctx context.Context, arg SaveSettingsParams) (Setting, error)
	SessionHasOpenOrders(ctx context.Context, sessionID sql.NullInt64) (int64, error)
	TouchSession(ctx context.Context, arg TouchSessionParams) (TouchSessionRow, error)
	UpdateMenuItem(ctx context.Context, arg UpdateMenuItemParams) (UpdateMenuItemRow, error)
	UpdateOrderPaymentStatus(ctx context.Context, arg UpdateOrderPaymentStatusParams) (UpdateOrderPaymentStatusRow, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (UpdateOrderStatusRow, error)
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (UpdateTableStatusRow, error)
	UpsertInventory(ctx context.Context, arg UpsertInventoryParams) (Inventory, error)
	UpsertQRCode(ctx context.Context, arg UpsertQRCodeParams) error
}

var _ Querier = (*Queries)(nil)
