// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"context"
)

type Querier interface {
	BestSellingItems(ctx context.Context, limit int64) ([]BestSellingItemsRow, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	CreateTable(ctx context.Context, arg CreateTableParams) (RestaurantTable, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DailySales(ctx context.Context, limit int64) ([]DailySalesRow, error)
	DeductIngredientStock(ctx context.Context, arg DeductIngredientStockParams) error
	GetMenuItem(ctx context.Context, id int64) (MenuItem, error)
	GetTableByToken(ctx context.Context, qrToken string) (RestaurantTable, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ListCategories(ctx context.Context) ([]MenuCategory, error)
	ListMenuItems(ctx context.Context) ([]MenuItem, error)
	ListOrderItems(ctx context.Context, orderID int64) ([]OrderItem, error)
	ListOrders(ctx context.Context, limit int64) ([]Order, error)
	ListPayments(ctx context.Context, limit int64) ([]Payment, error)
	ListTables(ctx context.Context) ([]RestaurantTable, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	LowStockIngredients(ctx context.Context) ([]Ingredient, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (RestaurantTable, error)
	UpsertMenuItem(ctx context.Context, arg UpsertMenuItemParams) (MenuItem, error)
}

var _ Querier = (*Queries)(nil)
