// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: receipts.sql

package database

import (
	"context"
	"database/sql"
)

const createReceipt = `-- name: CreateReceipt :one
INSERT INTO receipts (order_id, payment_id, receipt_number, payload_json)
VALUES (?, ?, ?, ?)
RETURNING id, order_id, payment_id, receipt_number, payload_json, created_at
`

type CreateReceiptParams struct {
	OrderID       int64         `json:"order_id"`
	PaymentID     sql.NullInt64 `json:"payment_id"`
	ReceiptNumber string        `json:"receipt_number"`
	PayloadJson   string        `json:"payload_json"`
}

func (q *Queries) CreateReceipt(ctx context.Context, arg CreateReceiptParams) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, createReceipt,
		arg.OrderID,
		arg.PaymentID,
		arg.ReceiptNumber,
		arg.PayloadJson,
	)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.ReceiptNumber,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}

const getReceiptByOrderID = `-- name: GetReceiptByOrderID :one
SELECT
  id,
  order_id,
  payment_id,
  receipt_number,
  payload_json,
  created_at
FROM receipts
WHERE order_id = ?
LIMIT 1
`

func (q *Queries) GetReceiptByOrderID(ctx context.Context, orderID int64) (Receipt, error) {
	row := q.db.QueryRowContext(ctx, getReceiptByOrderID, orderID)
	var i Receipt
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentID,
		&i.ReceiptNumber,
		&i.PayloadJson,
		&i.CreatedAt,
	)
	return i, err
}
