// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const activeSessionCount = `-- name: ActiveSessionCount :one
SELECT COUNT(*) FROM sessions WHERE status = 'active'
`

func (q *Queries) ActiveSessionCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, activeSessionCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const bestSellingItems = `-- name: BestSellingItems :many
SELECT mi.name, SUM(oi.quantity) AS quantity, SUM(oi.quantity * oi.unit_price_cents) AS revenue_cents
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
GROUP BY mi.id, mi.name
ORDER BY quantity DESC
LIMIT ?
`

type BestSellingItemsRow struct {
	Name         string          `json:"name"`
	Quantity     sql.NullFloat64 `json:"quantity"`
	RevenueCents sql.NullFloat64 `json:"revenue_cents"`
}

func (q *Queries) BestSellingItems(ctx context.Context, limit int64) ([]BestSellingItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, bestSellingItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BestSellingItemsRow
	for rows.Next() {
		var i BestSellingItemsRow
		if err := rows.Scan(&i.Name, &i.Quantity, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailySales = `-- name: DailySales :many
SELECT date(created_at) AS day, COUNT(*) AS order_count, SUM(total_cents) AS revenue_cents
FROM orders
WHERE status IN ('paid', 'served', 'ready') OR payment_status = 'paid'
GROUP BY date(created_at)
ORDER BY day DESC
LIMIT ?
`

type DailySalesRow struct {
	Day          interface{}     `json:"day"`
	OrderCount   int64           `json:"order_count"`
	RevenueCents sql.NullFloat64 `json:"revenue_cents"`
}

func (q *Queries) DailySales(ctx context.Context, limit int64) ([]DailySalesRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySales, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySalesRow
	for rows.Next() {
		var i DailySalesRow
		if err := rows.Scan(&i.Day, &i.OrderCount, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockProducts = `-- name: LowStockProducts :many
SELECT
  mi.id,
  mi.category_id,
  COALESCE(mc.name, '') AS category_name,
  mi.name,
  mi.description,
  mi.price_cents,
  mi.cost_cents,
  mi.image_url,
  mi.sku,
  mi.item_type,
  mi.sort_order,
  mi.active,
  COALESCE(inv.stock_qty, 0) AS stock_qty,
  COALESCE(inv.reorder_level, 0) AS reorder_level,
  COALESCE(inv.unit, 'pcs') AS unit,
  COALESCE(inv.track_stock, 1) AS track_stock,
  CASE
    WHEN COALESCE(inv.track_stock, 1) = 1 AND COALESCE(inv.stock_qty, 0) <= 0 THEN 1
    ELSE 0
  END AS out_of_stock,
  mi.created_at
FROM menu_items mi
JOIN inventory inv ON inv.product_id = mi.id
LEFT JOIN menu_categories mc ON mc.id = mi.category_id
WHERE COALESCE(inv.track_stock, 1) = 1
  AND COALESCE(inv.stock_qty, 0) <= COALESCE(inv.reorder_level, 0)
ORDER BY inv.stock_qty ASC, mi.name ASC
`

type LowStockProductsRow struct {
	ID           int64     `json:"id"`
	CategoryID   int64     `json:"category_id"`
	CategoryName string    `json:"category_name"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	PriceCents   int64     `json:"price_cents"`
	CostCents    int64     `json:"cost_cents"`
	ImageUrl     string    `json:"image_url"`
	Sku          string    `json:"sku"`
	ItemType     string    `json:"item_type"`
	SortOrder    int64     `json:"sort_order"`
	Active       int64     `json:"active"`
	StockQty     float64   `json:"stock_qty"`
	ReorderLevel float64   `json:"reorder_level"`
	Unit         string    `json:"unit"`
	TrackStock   int64     `json:"track_stock"`
	OutOfStock   int64     `json:"out_of_stock"`
	CreatedAt    time.Time `json:"created_at"`
}

func (q *Queries) LowStockProducts(ctx context.Context) ([]LowStockProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, lowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LowStockProductsRow
	for rows.Next() {
		var i LowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.CategoryName,
			&i.Name,
			&i.Description,
			&i.PriceCents,
			&i.CostCents,
			&i.ImageUrl,
			&i.Sku,
			&i.ItemType,
			&i.SortOrder,
			&i.Active,
			&i.StockQty,
			&i.ReorderLevel,
			&i.Unit,
			&i.TrackStock,
			&i.OutOfStock,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const openOrderCount = `-- name: OpenOrderCount :one
SELECT COUNT(*) FROM orders WHERE status NOT IN ('paid', 'cancelled')
`

func (q *Queries) OpenOrderCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, openOrderCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const paymentMethodStats = `-- name: PaymentMethodStats :many
SELECT method, COUNT(*) AS count, COALESCE(SUM(amount_cents), 0) AS revenue_cents
FROM payments
WHERE status = 'paid'
GROUP BY method
ORDER BY count DESC, method ASC
`

type PaymentMethodStatsRow struct {
	Method       string      `json:"method"`
	Count        int64       `json:"count"`
	RevenueCents interface{} `json:"revenue_cents"`
}

func (q *Queries) PaymentMethodStats(ctx context.Context) ([]PaymentMethodStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, paymentMethodStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentMethodStatsRow
	for rows.Next() {
		var i PaymentMethodStatsRow
		if err := rows.Scan(&i.Method, &i.Count, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revenueSnapshot = `-- name: RevenueSnapshot :one
SELECT
  COALESCE(SUM(CASE WHEN date(created_at) = date('now', 'localtime') AND status = 'paid' THEN amount_cents END), 0) AS daily_total_cents,
  COALESCE(SUM(CASE WHEN date(created_at) >= date('now', '-6 day', 'localtime') AND status = 'paid' THEN amount_cents END), 0) AS weekly_total_cents,
  COALESCE(SUM(CASE WHEN strftime('%Y-%m', created_at) = strftime('%Y-%m', 'now', 'localtime') AND status = 'paid' THEN amount_cents END), 0) AS monthly_total_cents
FROM payments
`

type RevenueSnapshotRow struct {
	DailyTotalCents   interface{} `json:"daily_total_cents"`
	WeeklyTotalCents  interface{} `json:"weekly_total_cents"`
	MonthlyTotalCents interface{} `json:"monthly_total_cents"`
}

func (q *Queries) RevenueSnapshot(ctx context.Context) (RevenueSnapshotRow, error) {
	row := q.db.QueryRowContext(ctx, revenueSnapshot)
	var i RevenueSnapshotRow
	err := row.Scan(&i.DailyTotalCents, &i.WeeklyTotalCents, &i.MonthlyTotalCents)
	return i, err
}
