// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package database

import (
	"context"
	"database/sql"
)

const bestSellingItems = `-- name: BestSellingItems :many
SELECT mi.name, SUM(oi.quantity) AS quantity, SUM(oi.quantity * oi.unit_price_cents) AS revenue_cents
FROM order_items oi
JOIN menu_items mi ON mi.id = oi.menu_item_id
GROUP BY mi.id, mi.name
ORDER BY quantity DESC
LIMIT ?
`

type BestSellingItemsRow struct {
	Name         string          `json:"name"`
	Quantity     sql.NullFloat64 `json:"quantity"`
	RevenueCents sql.NullFloat64 `json:"revenue_cents"`
}

func (q *Queries) BestSellingItems(ctx context.Context, limit int64) ([]BestSellingItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, bestSellingItems, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BestSellingItemsRow
	for rows.Next() {
		var i BestSellingItemsRow
		if err := rows.Scan(&i.Name, &i.Quantity, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dailySales = `-- name: DailySales :many
SELECT date(created_at) AS day, COUNT(*) AS order_count, SUM(total_cents) AS revenue_cents
FROM orders
WHERE status IN ('paid','served','ready')
GROUP BY date(created_at)
ORDER BY day DESC
LIMIT ?
`

type DailySalesRow struct {
	Day          interface{}     `json:"day"`
	OrderCount   int64           `json:"order_count"`
	RevenueCents sql.NullFloat64 `json:"revenue_cents"`
}

func (q *Queries) DailySales(ctx context.Context, limit int64) ([]DailySalesRow, error) {
	rows, err := q.db.QueryContext(ctx, dailySales, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DailySalesRow
	for rows.Next() {
		var i DailySalesRow
		if err := rows.Scan(&i.Day, &i.OrderCount, &i.RevenueCents); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lowStockIngredients = `-- name: LowStockIngredients :many
SELECT id, name, unit, stock_qty, low_stock_qty FROM ingredients WHERE stock_qty <= low_stock_qty ORDER BY stock_qty ASC
`

func (q *Queries) LowStockIngredients(ctx context.Context) ([]Ingredient, error) {
	rows, err := q.db.QueryContext(ctx, lowStockIngredients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Unit,
			&i.StockQty,
			&i.LowStockQty,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
