// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const closeSession = `-- name: CloseSession :exec
UPDATE sessions
SET
  status = 'closed',
  ended_at = CURRENT_TIMESTAMP,
  last_seen_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) CloseSession(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, closeSession, id)
	return err
}

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (table_id, token, customer_name)
VALUES (?, ?, ?)
RETURNING id, table_id, '' AS table_number, token, customer_name, status, started_at, last_seen_at, ended_at
`

type CreateSessionParams struct {
	TableID      int64  `json:"table_id"`
	Token        string `json:"token"`
	CustomerName string `json:"customer_name"`
}

type CreateSessionRow struct {
	ID           int64        `json:"id"`
	TableID      int64        `json:"table_id"`
	Column3      string       `json:"column_3"`
	Token        string       `json:"token"`
	CustomerName string       `json:"customer_name"`
	Status       string       `json:"status"`
	StartedAt    time.Time    `json:"started_at"`
	LastSeenAt   time.Time    `json:"last_seen_at"`
	EndedAt      sql.NullTime `json:"ended_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRowContext(ctx, createSession, arg.TableID, arg.Token, arg.CustomerName)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Column3,
		&i.Token,
		&i.CustomerName,
		&i.Status,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
	)
	return i, err
}

const getSessionByToken = `-- name: GetSessionByToken :one
SELECT
  s.id,
  s.table_id,
  COALESCE(t.number, '') AS table_number,
  s.token,
  s.customer_name,
  s.status,
  s.started_at,
  s.last_seen_at,
  s.ended_at
FROM sessions s
JOIN restaurant_tables t ON t.id = s.table_id
WHERE s.token = ?
LIMIT 1
`

type GetSessionByTokenRow struct {
	ID           int64        `json:"id"`
	TableID      int64        `json:"table_id"`
	TableNumber  string       `json:"table_number"`
	Token        string       `json:"token"`
	CustomerName string       `json:"customer_name"`
	Status       string       `json:"status"`
	StartedAt    time.Time    `json:"started_at"`
	LastSeenAt   time.Time    `json:"last_seen_at"`
	EndedAt      sql.NullTime `json:"ended_at"`
}

func (q *Queries) GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionByToken, token)
	var i GetSessionByTokenRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.TableNumber,
		&i.Token,
		&i.CustomerName,
		&i.Status,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :one
UPDATE sessions
SET
  customer_name = CASE WHEN ? = '' THEN customer_name ELSE ? END,
  last_seen_at = CURRENT_TIMESTAMP
WHERE token = ?
RETURNING id, table_id, '' AS table_number, token, customer_name, status, started_at, last_seen_at, ended_at
`

type TouchSessionParams struct {
	Column1      interface{} `json:"column_1"`
	CustomerName string      `json:"customer_name"`
	Token        string      `json:"token"`
}

type TouchSessionRow struct {
	ID           int64        `json:"id"`
	TableID      int64        `json:"table_id"`
	Column3      string       `json:"column_3"`
	Token        string       `json:"token"`
	CustomerName string       `json:"customer_name"`
	Status       string       `json:"status"`
	StartedAt    time.Time    `json:"started_at"`
	LastSeenAt   time.Time    `json:"last_seen_at"`
	EndedAt      sql.NullTime `json:"ended_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) (TouchSessionRow, error) {
	row := q.db.QueryRowContext(ctx, touchSession, arg.Column1, arg.CustomerName, arg.Token)
	var i TouchSessionRow
	err := row.Scan(
		&i.ID,
		&i.TableID,
		&i.Column3,
		&i.Token,
		&i.CustomerName,
		&i.Status,
		&i.StartedAt,
		&i.LastSeenAt,
		&i.EndedAt,
	)
	return i, err
}
