// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package database

import (
	"context"
)

const getSettings = `-- name: GetSettings :one
SELECT
  id,
  business_name,
  business_type,
  phone,
  currency_code,
  mpesa_till,
  receipt_footer,
  created_at,
  updated_at
FROM settings
WHERE id = 1
LIMIT 1
`

func (q *Queries) GetSettings(ctx context.Context) (Setting, error) {
	row := q.db.QueryRowContext(ctx, getSettings)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BusinessType,
		&i.Phone,
		&i.CurrencyCode,
		&i.MpesaTill,
		&i.ReceiptFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveSettings = `-- name: SaveSettings :one
INSERT INTO settings (
  id,
  business_name,
  business_type,
  phone,
  currency_code,
  mpesa_till,
  receipt_footer,
  created_at,
  updated_at
)
VALUES (1, ?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
ON CONFLICT(id) DO UPDATE SET
  business_name = excluded.business_name,
  business_type = excluded.business_type,
  phone = excluded.phone,
  currency_code = excluded.currency_code,
  mpesa_till = excluded.mpesa_till,
  receipt_footer = excluded.receipt_footer,
  updated_at = CURRENT_TIMESTAMP
RETURNING
  id,
  business_name,
  business_type,
  phone,
  currency_code,
  mpesa_till,
  receipt_footer,
  created_at,
  updated_at
`

type SaveSettingsParams struct {
	BusinessName  string `json:"business_name"`
	BusinessType  string `json:"business_type"`
	Phone         string `json:"phone"`
	CurrencyCode  string `json:"currency_code"`
	MpesaTill     string `json:"mpesa_till"`
	ReceiptFooter string `json:"receipt_footer"`
}

func (q *Queries) SaveSettings(ctx context.Context, arg SaveSettingsParams) (Setting, error) {
	row := q.db.QueryRowContext(ctx, saveSettings,
		arg.BusinessName,
		arg.BusinessType,
		arg.Phone,
		arg.CurrencyCode,
		arg.MpesaTill,
		arg.ReceiptFooter,
	)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.BusinessName,
		&i.BusinessType,
		&i.Phone,
		&i.CurrencyCode,
		&i.MpesaTill,
		&i.ReceiptFooter,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
