// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tables.sql

package database

import (
	"context"
)

const createTable = `-- name: CreateTable :one
INSERT INTO restaurant_tables (number, seats, qr_token) VALUES (?, ?, ?)
RETURNING id, number, seats, status, qr_token, created_at
`

type CreateTableParams struct {
	Number  string `json:"number"`
	Seats   int64  `json:"seats"`
	QrToken string `json:"qr_token"`
}

func (q *Queries) CreateTable(ctx context.Context, arg CreateTableParams) (RestaurantTable, error) {
	row := q.db.QueryRowContext(ctx, createTable, arg.Number, arg.Seats, arg.QrToken)
	var i RestaurantTable
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Seats,
		&i.Status,
		&i.QrToken,
		&i.CreatedAt,
	)
	return i, err
}

const getTableByToken = `-- name: GetTableByToken :one
SELECT id, number, seats, status, qr_token, created_at FROM restaurant_tables WHERE qr_token = ? LIMIT 1
`

func (q *Queries) GetTableByToken(ctx context.Context, qrToken string) (RestaurantTable, error) {
	row := q.db.QueryRowContext(ctx, getTableByToken, qrToken)
	var i RestaurantTable
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Seats,
		&i.Status,
		&i.QrToken,
		&i.CreatedAt,
	)
	return i, err
}

const listTables = `-- name: ListTables :many
SELECT id, number, seats, status, qr_token, created_at FROM restaurant_tables ORDER BY CAST(number AS INTEGER), number
`

func (q *Queries) ListTables(ctx context.Context) ([]RestaurantTable, error) {
	rows, err := q.db.QueryContext(ctx, listTables)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RestaurantTable
	for rows.Next() {
		var i RestaurantTable
		if err := rows.Scan(
			&i.ID,
			&i.Number,
			&i.Seats,
			&i.Status,
			&i.QrToken,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTableStatus = `-- name: UpdateTableStatus :one
UPDATE restaurant_tables SET status = ? WHERE id = ?
RETURNING id, number, seats, status, qr_token, created_at
`

type UpdateTableStatusParams struct {
	Status string `json:"status"`
	ID     int64  `json:"id"`
}

func (q *Queries) UpdateTableStatus(ctx context.Context, arg UpdateTableStatusParams) (RestaurantTable, error) {
	row := q.db.QueryRowContext(ctx, updateTableStatus, arg.Status, arg.ID)
	var i RestaurantTable
	err := row.Scan(
		&i.ID,
		&i.Number,
		&i.Seats,
		&i.Status,
		&i.QrToken,
		&i.CreatedAt,
	)
	return i, err
}
